trigger:
  branches:
    include:
      - main  # Replace 'main' with the branch you want to trigger the pipeline on.

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      npm install
      npm run build
    displayName: 'Install and Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/out'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive Build Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
    displayName: 'Publish Build Artifacts'
